In [ ]:
import pandas as pd

df = pd.read_csv('FA-SQL-DATA.csv')

In [ ]:
# DATA UNDERSTANDING

df.head()
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48744 entries, 0 to 48743
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   NAME_CONTRACT_TYPE   48744 non-null  object
 1   GENDER               48744 non-null  object
 2   Gender_code          48744 non-null  int64
 3   INCOME               48744 non-null  int64
 4   CREDIT               48744 non-null  int64
 5   ANNUITY              48744 non-null  float64
 6   AMT_GOODS_PRICE      48744 non-null  int64
 7   NAME_TYPE_SUITE      48744 non-null  object
 8   NAME_INCOME_TYPE     48744 non-null  object
 9   DAYS_BIRTH           48744 non-null  int64
 10  AGE                  48744 non-null  int64
 11  DAYS_EMPLOYED        48744 non-null  int64
 12  EMPLOYED_YEARS       48744 non-null  int64
 13  DAYS_REGISTRATION    48744 non-null  int64
 14  OCCUPATION           48744 non-null  object
 15  FAM_MEMBERS          48744 non-null  int64
 16  ORGANIZATION_TYPE    48744 non-null  object
 17  LOAN_TO_INCOM_RATIO  48744 non-null  float64
 18  EMI_RATIO            48744 non-null  float64
 19  INCOME/MEMBER        48744 non-null  int64
 20  High_Risk            48744 non-null  bool
 21  risk_label           48744 non-null  object
 22  risk_flag            48744 non-null  int64
dtypes: bool(1), float64(3), int64(12), object(7)
memory usage: 8.2+ MB

,Gender_code,INCOME,CREDIT,ANNUITY,AMT_GOODS_PRICE,DAYS_BIRTH,AGE,DAYS_EMPLOYED,EMPLOYED_YEARS,DAYS_REGISTRATION,FAM_MEMBERS,LOAN_TO_INCOM_RATIO,EMI_RATIO,INCOME/MEMBER,risk_flag
count,48744.000000,4.874400e+04,4.874400e+04,48744.000000,4.874400e+04,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,48744.000000,4.874400e+04,48744.000000
mean,0.329600,1.784318e+05,5.167405e+05,29424.651219,4.626188e+05,-16068.084605,44.014894,67485.366322,13.606782,-4967.652716,2.146767,3.168612,0.183266,9.807881e+04,0.015304
std,0.470073,1.015226e+05,3.653970e+05,16012.584824,3.367102e+05,4325.900393,11.854680,144348.507136,9.732436,3552.612035,0.890423,2.137352,0.099102,7.405667e+04,0.122762
min,0.000000,2.694200e+04,4.500000e+04,2295.000000,4.500000e+04,-25195.000000,20.000000,-17463.000000,0.000000,-23722.000000,1.000000,0.100000,0.000000,5.850000e+03,0.000000
25%,0.000000,1.125000e+05,2.606400e+05,17973.000000,2.250000e+05,-19637.000000,34.000000,-2910.000000,5.000000,-7459.250000,2.000000,1.700000,0.100000,5.400000e+04,0.000000
50%,0.000000,1.575000e+05,4.500000e+05,26199.000000,3.960000e+05,-15785.000000,43.000000,-1293.000000,12.000000,-4490.000000,2.000000,2.700000,0.200000,7.875000e+04,0.000000
75%,1.000000,2.250000e+05,6.750000e+05,37390.500000,6.300000e+05,-12496.000000,54.000000,-296.000000,20.000000,-1901.000000,3.000000,4.000000,0.200000,1.200000e+05,0.000000
max,1.000000,4.410000e+06,2.245500e+06,180576.000000,2.245500e+06,-7338.000000,69.000000,365243.000000,65.000000,0.000000,21.000000,30.400000,2.000000,4.410000e+06,1.000000

In [ ]:
#CHECK DISTRIBUTION

df['risk_label'].value_counts()

risk_label
Low Risk       34446
Medium Risk    13552
High Risk        746
Name: count, dtype: int64

In [ ]:
# Convert Risk Label → Numeric
df['risk_flag'] = df['risk_label'].map({
    'High Risk': 1,
    'Medium Risk': 0,
    'Low Risk': 0
})

In [ ]:
# Feature Selection

features = [
    'INCOME',
    'CREDIT',
    'ANNUITY',
    'AGE',
    'EMPLOYED_YEARS',
    'FAM_MEMBERS',
    'INCOME/MEMBER'
]

In [ ]:
# Train-Test Split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
# Model (Logistic Regression)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
# Predictions

y_pred = model.predict(X_test)

In [ ]:
# Evaluate Model

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9601
           1       1.00      0.68      0.81       148

    accuracy                           1.00      9749
   macro avg       1.00      0.84      0.90      9749
weighted avg       1.00      1.00      0.99      9749

In [ ]:
# Feature Importance

import pandas as pd

importance = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_[0]
})

importance.sort_values(by='Coefficient', ascending=False)

               Feature  Coefficient
1            EMI_RATIO    23.625364
0  LOAN_TO_INCOM_RATIO     0.203094